# After https://github.com/conda-forge/torchvision-feedstock/blob/main/recipe/conda_build_config.yaml
c_stdlib_version:   # [osx and x86_64]
  - 10.15           # [osx and x86_64]
MACOSX_SDK_VERSION:         # [osx]
  - 13.3                    # [osx]

c_stdlib_version:                                   # [linux and aarch64]
  - 2.17                                            # [linux and aarch64]
  - 2.17                                            # [linux and aarch64]
  - 2.28                                            # [linux and aarch64]
  - 2.28                                            # [linux and aarch64]
cuda_compiler:                                      # [linux and aarch64]
  - None                                            # [linux and aarch64]
  - nvcc                                            # [linux and aarch64]
  - cuda-nvcc                                       # [linux and aarch64]
  - cuda-nvcc                                       # [linux and aarch64]
cuda_compiler_version:                              # [linux and aarch64]
  - None                                            # [linux and aarch64]
  - 11.8                                            # [linux and aarch64]
  - 12.0                                            # [linux and aarch64]
  - 12.4                                            # [linux and aarch64]

zip_keys:                                 
  - c_stdlib_version
  - cuda_compiler
  - cuda_compiler_version
