c_stdlib_version:
  - 2.17
  - 2.17
  - 2.28
  - 2.28
  - 2.28

cuda_compiler_version:
  - None
  - 11.8
  - None
  - 11.8
  - 12.0 
  - 12.4
# leaving cuda 12.6 out for now, torch cuda not available
#  - 12.6 # [c_stdlib_version != 2.17] 
