{% set name = "heat" %}
{% set version = "1.5.1" %}
{% set cuda_compiler_version = os.environ.get('cuda_compiler_version', 'None') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/heat-{{ version }}.tar.gz
  sha256: 95fea9daec6c2d5f0453159dbcd5efb26cb23997f0981e49fe9793a2fd342313

build:
  number: 2
  script_env: OMPI_MCA_plm_rsh_agent=  # [linux or aarch64]
  script: {{ PYTHON }} -m pip install . -vv
  # pytorch no longer supports cuda<12
  skip: true  # [win or cuda_compiler_version == "11.8"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                 # [cuda_compiler_version == "None"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    # GPU requirements
    {% if cuda_compiler_version != 'None' %}
    - cudnn
    - nccl
    - magma
    - cuda-version {{ cuda_compiler_version }}
    {% endif %}
    # everything else
    - python
    - pip
    - openmpi
    - setuptools
  run:
    - python
    - openmpi
    - mpi4py >=3.0.0
    - numpy >=1.22,<2.0.0
    - pytorch >=2.0.0,<2.6.1
    - scipy >=0.14.0
    - pillow >=6.0.0
    - torchvision >=0.15.2,<0.21.1
    - h5py >=2.8.0
    - h5py * mpi*
    - netCDF4 >=1.5.6
    - scikit-learn >=0.24.0
    - libgomp  # [linux or aarch64]
    - llvm-openmp  # [osx]

test:
  imports:
    - heat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/helmholtz-analytics/heat
  summary: A Python framework for data-intensive analytics and machine learning.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/helmholtz-analytics/heat
  doc_url: https://heat.readthedocs.io

extra:
  recipe-maintainers:
    - ClaudiaComito
    - mrfh92
    - JuanPedroGHM
