{% set name = "heat" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heat-{{ version }}.tar.gz
  sha256: a2e2d7f0c1f340ab2597f2b9c02563f0057419a53287fbf4cdf1a7934bc6d60b

build:
  skip: true  # [win]
  script_env: OMPI_MCA_plm_rsh_agent=  # [linux]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - openmpi
    - setuptools
  run:
    - python
    - openmpi
    - mpi4py >=3.0.0
    - numpy >=1.22,<2.0.0
    - pytorch::pytorch >=1.12.0,<2.3.2
    - scipy >=0.14.0
    - pillow >=6.0.0
    - pytorch::torchvision >=0.8.0
    - h5py >=2.8.0=mpi*
    - netCDF4 >=1.5.6
    - scikit-learn >=0.24.0
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

test:
  imports:
    - heat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/helmholtz-analytics/heat
  summary: A Python framework for data-intensive analytics and machine learning.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/helmholtz-analytics/heat
  doc_url: https://heat.readthedocs.io

extra:
  recipe-maintainers:
    - ClaudiaComito
    - mrfh92
    - JuanPedroGHM
